#!/usr/bin/perl -w

#Gera uma lista de palavras flexionadas dos lemas do dicion·rio

#undef $/;
#$/='';
my $dict = shift or die;

open(F,qq{awk -F / '{print \$1 "/" \$3}' $dict | jspell -e -o '' |}) or die;
open(F1,"| grep -v '#' |grep '[a-zA-Z‡ÈÛ·˙]' | sort -u") or die;

while(<F>){
  s/[-= ,\n]+/\n/g;
  next if m!^#!;
  print F1 "$_\n";
}

close F1;
close F;

