#---------------------------------------------------------------------
#  
# This is   ASPELL/portugues/Makefile
#
# THIS DOES NOT WORK - USE configure & make
#---------------------------------------------------------------------

DICT = portugues.aspell

CONFIG = portugues.dat
PHONET = portugues_phone.dat

pkgdatadir = `aspell config data-dir`

pkglibdir  = `aspell config dict-dir`

pspell_pkgdatadir = `pspell-config pkgdatadir`

INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644

DATE=`date +%Y%m%d`

all: pt-aspell.pwli portugues

portugues: $(DICT) $(PHONET) $(CONFIG)
	cp $(pkgdatadir)/iso*8859-1.* ./
	aspell --data-dir=. --lang=portugues create master ./portugues < $(DICT)

pt-aspell.pwli:
	echo $(pkglibdir)/portugues > pt-aspell.pwli

install: portugues
	${INSTALL_DATA} $(PHONET) $(pkgdatadir)/
	echo ${INSTALL_DATA} $(CONFIG) $(pkgdatadir)/
	echo ${INSTALL_DATA} portugues  $(pkglibdir)/
	echo ${INSTALL_DATA} pt-aspell.pwli $(pspell_pkgdatadir)/
	${INSTALL_DATA} $(CONFIG) $(pkgdatadir)/
	${INSTALL_DATA} portugues  $(pkglibdir)/
	${INSTALL_DATA} pt-aspell.pwli $(pspell_pkgdatadir)/



clean:
	rm -f *~ portugues EXCLUDE pt-aspell.pwli iso8859-1.dat portugues.aspell
