# -*- makefile -*- 

myspell-all: # myspell myspell-ao-tgz myspell-preao-tgz

myspell: # myspell-ao myspell-preao



dirs ::
	mkdir -p $(MYOUT)-ao
	mkdir -p $(MYOUT)-preao

realclean ::
	@ echo "Cleaning myspell files"
	rm -fr $(MYOUT)-ao
	rm -fr $(MYOUT)-preao
