## -*- makefile -*-

DIRS+=$(OOUT)-ao $(OOUT)-preao


$(MOUT)-ao:
	mkdir -p $(MOUT)-ao


$(MOUT)-preao:
	mkdir -p $(MOUT)-preao


# 1. copiar ficheiros
#   pt-PT-AO.{aff,dic} }
#   pt-PT-preAO.{aff,dic} }